# configs/tournaments_m_db.py

"""
Defines the master database of all possible men's pro tour tournaments.

Keys:
- id: A unique identifier for the tournament.
- name: The display name of the tournament.
- city: The host city.
- country: The 3-letter country code.
- level: Point value (2000, 1000, 500, 250).
- weeks: A list of the week numbers (1-52) the tournament occupies.
- surface: 'Hard', 'Clay', 'Grass', or 'Hard (Indoor)'.
- status: 'Fixed' (never changes) or 'Rotating' (can be swapped out).
- draw_size: Total players in the main draw.
- main_draw_entrants: Players who get in via direct entry (ranking).
- qualifiers: Slots reserved for players from the qualifying tournament.
- wildcards: Slots for special invitations.
"""
from configparser import DuplicateSectionError

MENS_PRO_TOUR_DB = [
    # ======================================================
    # 1. FIXED TOURNAMENTS (13 total)
    # ======================================================

    # --- Grand Slams (Level 2000) ---
    {'id': 'GS01', 'name': 'Aussie Slam', 'city': 'Melbourne', 'country': 'AUS', 'level': 2000, 'weeks': [3, 4],
     'surface': 'Hard', 'status': 'Fixed', 'draw_size': 128, 'main_draw_entrants': 104, 'qualifiers': 16,
     'wildcards': 8},
    {'id': 'GS02', 'name': 'French Slam', 'city': 'Paris', 'country': 'FRA', 'level': 2000, 'weeks': [21, 22],
     'surface': 'Clay', 'status': 'Fixed', 'draw_size': 128, 'main_draw_entrants': 104, 'qualifiers': 16,
     'wildcards': 8},
    {'id': 'GS03', 'name': 'The Grand All England', 'city': 'London', 'country': 'GBR', 'level': 2000,
     'weeks': [26, 27], 'surface': 'Grass', 'status': 'Fixed', 'draw_size': 128, 'main_draw_entrants': 104,
     'qualifiers': 16, 'wildcards': 8},
    {'id': 'GS04', 'name': 'US Slam', 'city': 'New York', 'country': 'USA', 'level': 2000, 'weeks': [35, 36],
     'surface': 'Hard', 'status': 'Fixed', 'draw_size': 128, 'main_draw_entrants': 104, 'qualifiers': 16,
     'wildcards': 8},

    # --- Masters (Level 1000) ---
    {'id': 'M1000_01', 'name': 'Indian Wells', 'city': 'Indian Wells', 'country': 'USA', 'level': 1000,
     'weeks': [9, 10], 'surface': 'Hard', 'status': 'Fixed', 'draw_size': 96, 'main_draw_entrants': 76,
     'qualifiers': 12, 'wildcards': 8},
    {'id': 'M1000_02', 'name': 'Miami', 'city': 'Miami', 'country': 'USA', 'level': 1000, 'weeks': [11, 12],
     'surface': 'Hard', 'status': 'Fixed', 'draw_size': 96, 'main_draw_entrants': 76, 'qualifiers': 12, 'wildcards': 8},
    {'id': 'M1000_03', 'name': 'Monte-Carlo', 'city': 'Monte Carlo', 'country': 'MON', 'level': 1000, 'weeks': [14],
     'surface': 'Clay', 'status': 'Fixed', 'draw_size': 56, 'main_draw_entrants': 44, 'qualifiers': 8, 'wildcards': 4},
    {'id': 'M1000_04', 'name': 'Madrid', 'city': 'Madrid', 'country': 'ESP', 'level': 1000, 'weeks': [16, 17],
     'surface': 'Clay', 'status': 'Fixed', 'draw_size': 96, 'main_draw_entrants': 76, 'qualifiers': 12, 'wildcards': 8},
    {'id': 'M1000_05', 'name': 'Rome', 'city': 'Rome', 'country': 'ITA', 'level': 1000, 'weeks': [18, 19],
     'surface': 'Clay', 'status': 'Fixed', 'draw_size': 96, 'main_draw_entrants': 76, 'qualifiers': 12, 'wildcards': 8},
    {'id': 'M1000_06', 'name': 'Canada', 'city': 'Toronto', 'country': 'CAN', 'level': 1000, 'weeks': [31],
     'surface': 'Hard', 'status': 'Fixed', 'draw_size': 56, 'main_draw_entrants': 44, 'qualifiers': 8, 'wildcards': 4},
    {'id': 'M1000_07', 'name': 'Cincinnati', 'city': 'Cincinnati', 'country': 'USA', 'level': 1000, 'weeks': [32, 33],
     'surface': 'Hard', 'status': 'Fixed', 'draw_size': 96, 'main_draw_entrants': 76, 'qualifiers': 12, 'wildcards': 8},
    {'id': 'M1000_08', 'name': 'Shanghai', 'city': 'Shanghai', 'country': 'CHN', 'level': 1000, 'weeks': [40, 41],
     'surface': 'Hard', 'status': 'Fixed', 'draw_size': 96, 'main_draw_entrants': 76, 'qualifiers': 12, 'wildcards': 8},
    {'id': 'M1000_09', 'name': 'Paris', 'city': 'Paris', 'country': 'FRA', 'level': 1000, 'weeks': [44],
     'surface': 'Hard (Indoor)', 'status': 'Fixed', 'draw_size': 56, 'main_draw_entrants': 44, 'qualifiers': 8,
     'wildcards': 4},

    # ======================================================
    # 2. ROTATING TOURNAMENTS (xx total)
    # ======================================================

    # --- Calendar 500s (16 tournaments from 2026 schedule) ---
    {'id': 'ATP500_01', 'name': 'Rotterdam', 'city': 'Rotterdam', 'country': 'NED', 'level': 500, 'weeks': [6],
     'surface': 'Hard (Indoor)', 'status': 'Rotating', 'draw_size': 32, 'main_draw_entrants': 24, 'qualifiers': 4,
     'wildcards': 4},
    {'id': 'ATP500_14', 'name': 'Dallas', 'city': 'Dallas', 'country': 'USA', 'level': 500, 'weeks': [6],
     'surface': 'Hard (Indoor)', 'status': 'Rotating', 'draw_size': 32, 'main_draw_entrants': 24, 'qualifiers': 4,
     'wildcards': 4},
    {'id': 'ATP500_02', 'name': 'Rio de Janeiro', 'city': 'Rio de Janeiro', 'country': 'BRA', 'level': 500,
     'weeks': [7], 'surface': 'Clay', 'status': 'Rotating', 'draw_size': 32, 'main_draw_entrants': 24, 'qualifiers': 4,
     'wildcards': 4},
    {'id': 'ATP500_15', 'name': 'Doha', 'city': 'Doha', 'country': 'QAT', 'level': 500, 'weeks': [7],
     'surface': 'Hard', 'status': 'Rotating', 'draw_size': 32, 'main_draw_entrants': 24, 'qualifiers': 4,
     'wildcards': 4},
    {'id': 'ATP500_03', 'name': 'Dubai', 'city': 'Dubai', 'country': 'UAE', 'level': 500, 'weeks': [8],
     'surface': 'Hard', 'status': 'Rotating', 'draw_size': 32, 'main_draw_entrants': 24, 'qualifiers': 4,
     'wildcards': 4},
    {'id': 'ATP500_04', 'name': 'Acapulco', 'city': 'Acapulco', 'country': 'MEX', 'level': 500, 'weeks': [8],
     'surface': 'Hard', 'status': 'Rotating', 'draw_size': 32, 'main_draw_entrants': 24, 'qualifiers': 4,
     'wildcards': 4},
    {'id': 'ATP500_05', 'name': 'Barcelona', 'city': 'Barcelona', 'country': 'ESP', 'level': 500, 'weeks': [15],
     'surface': 'Clay', 'status': 'Rotating', 'draw_size': 32, 'main_draw_entrants': 24, 'qualifiers': 4,
     'wildcards': 4},
    {'id': 'ATP500_16', 'name': 'Munich', 'city': 'Munich', 'country': 'GER', 'level': 500, 'weeks': [15],
     'surface': 'Clay', 'status': 'Rotating', 'draw_size': 32, 'main_draw_entrants': 24, 'qualifiers': 4,
     'wildcards': 4},
    {'id': 'ATP500_06', 'name': 'Halle', 'city': 'Halle', 'country': 'GER', 'level': 500, 'weeks': [24],
     'surface': 'Grass', 'status': 'Rotating', 'draw_size': 32, 'main_draw_entrants': 24, 'qualifiers': 4,
     'wildcards': 4},
    {'id': 'ATP500_07', 'name': 'London', 'city': 'London', 'country': 'GBR', 'level': 500, 'weeks': [24],
     'surface': 'Grass', 'status': 'Rotating', 'draw_size': 32, 'main_draw_entrants': 24, 'qualifiers': 4,
     'wildcards': 4},
    {'id': 'ATP500_08', 'name': 'Hamburg', 'city': 'Hamburg', 'country': 'GER', 'level': 500, 'weeks': [20],
     'surface': 'Clay', 'status': 'Rotating', 'draw_size': 32, 'main_draw_entrants': 24, 'qualifiers': 4,
     'wildcards': 4},
    {'id': 'ATP500_09', 'name': 'Washington', 'city': 'Washington D.C.', 'country': 'USA', 'level': 500, 'weeks': [30],
     'surface': 'Hard', 'status': 'Rotating', 'draw_size': 32, 'main_draw_entrants': 24, 'qualifiers': 4,
     'wildcards': 4},
    {'id': 'ATP500_10', 'name': 'Beijing', 'city': 'Beijing', 'country': 'CHN', 'level': 500, 'weeks': [39],
     'surface': 'Hard', 'status': 'Rotating', 'draw_size': 32, 'main_draw_entrants': 24, 'qualifiers': 4,
     'wildcards': 4},
    {'id': 'ATP500_11', 'name': 'Tokyo', 'city': 'Tokyo', 'country': 'JPN', 'level': 500, 'weeks': [39],
     'surface': 'Hard', 'status': 'Rotating', 'draw_size': 32, 'main_draw_entrants': 24, 'qualifiers': 4,
     'wildcards': 4},
    {'id': 'ATP500_12', 'name': 'Vienna', 'city': 'Vienna', 'country': 'AUT', 'level': 500, 'weeks': [43],
     'surface': 'Hard (Indoor)', 'status': 'Rotating', 'draw_size': 32, 'main_draw_entrants': 24, 'qualifiers': 4,
     'wildcards': 4},
    {'id': 'ATP500_13', 'name': 'Basel', 'city': 'Basel', 'country': 'SUI', 'level': 500, 'weeks': [43],
     'surface': 'Hard (Indoor)', 'status': 'Rotating', 'draw_size': 32, 'main_draw_entrants': 24, 'qualifiers': 4,
     'wildcards': 4},

    # # --- Pool Candidate 500s (10 tournaments for variety) ---
    # START HERE NEXT TIME DUDE,
    # RIGHT HERE,
    # ABOVE HERE IS FINE YOU ALREADY FIXED IT
    {'id': 'ATP500_P01', 'name': 'Salt Lake City', 'city': 'Salt Lake City', 'country': 'USA', 'level': 500, 'weeks': [7],
     'surface': 'Hard (Indoor)', 'status': 'Rotating', 'draw_size': 32, 'main_draw_entrants': 24, 'qualifiers': 4,
     'wildcards': 4},
    {'id': 'ATP500_P02', 'name': 'Munich', 'city': 'Munich', 'country': 'GER', 'level': 500, 'weeks': [15],
     'surface': 'Clay', 'status': 'Rotating', 'draw_size': 32, 'main_draw_entrants': 24, 'qualifiers': 4,
     'wildcards': 4},
    {'id': 'ATP500_P03', 'name': 'Buenos Aires', 'city': 'Buenos Aires', 'country': 'ARG', 'level': 500, 'weeks': [7],
     'surface': 'Clay', 'status': 'Rotating', 'draw_size': 32, 'main_draw_entrants': 24, 'qualifiers': 4,
     'wildcards': 4},
    {'id': 'ATP500_P04', 'name': 'Valencia', 'city': 'Valencia', 'country': 'ESP', 'level': 500, 'weeks': [41],
     'surface': 'Hard (Indoor)', 'status': 'Rotating', 'draw_size': 32, 'main_draw_entrants': 24, 'qualifiers': 4,
     'wildcards': 4},
    {'id': 'ATP500_P05', 'name': 'Manchester', 'city': 'Manchester', 'country': 'GBR', 'level': 500, 'weeks': [25],
     'surface': 'Grass', 'status': 'Rotating', 'draw_size': 32, 'main_draw_entrants': 24, 'qualifiers': 4,
     'wildcards': 4},
    {'id': 'ATP500_P06', 'name': 'Seoul', 'city': 'Seoul', 'country': 'KOR', 'level': 500, 'weeks': [38],
     'surface': 'Hard', 'status': 'Rotating', 'draw_size': 32, 'main_draw_entrants': 24, 'qualifiers': 4,
     'wildcards': 4},
    {'id': 'ATP500_P07', 'name': 'St. Petersburg', 'city': 'St. Petersburg', 'country': 'RUS', 'level': 500,
     'weeks': [41], 'surface': 'Hard (Indoor)', 'status': 'Rotating', 'draw_size': 32, 'main_draw_entrants': 24,
     'qualifiers': 4, 'wildcards': 4},
    {'id': 'ATP500_P08', 'name': 'Sao Paulo', 'city': 'Sao Paulo', 'country': 'BRA', 'level': 500, 'weeks': [7],
     'surface': 'Clay (Indoor)', 'status': 'Rotating', 'draw_size': 32, 'main_draw_entrants': 24, 'qualifiers': 4,
     'wildcards': 4},
    {'id': 'ATP500_P09', 'name': 'Gstaad', 'city': 'Gstaad', 'country': 'SUI', 'level': 500, 'weeks': [28],
     'surface': 'Clay', 'status': 'Rotating', 'draw_size': 32, 'main_draw_entrants': 24, 'qualifiers': 4,
     'wildcards': 4},
    {'id': 'ATP500_P10', 'name': 'Kuala Lumpur', 'city': 'Kuala Lumpur', 'country': 'MAS', 'level': 500, 'weeks': [37],
     'surface': 'Hard', 'status': 'Rotating', 'draw_size': 32, 'main_draw_entrants': 24, 'qualifiers': 4,
     'wildcards': 4},

    # --- Calendar 250s (39 tournaments from 2026 schedule) ---
    {'id': 'ATP250_01', 'name': 'Brisbane', 'city': 'Brisbane', 'country': 'AUS', 'level': 250, 'weeks': [1],
     'surface': 'Hard', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_02', 'name': 'Hong Kong', 'city': 'Hong Kong', 'country': 'HKG', 'level': 250, 'weeks': [1],
     'surface': 'Hard', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_03', 'name': 'Adelaide', 'city': 'Adelaide', 'country': 'AUS', 'level': 250, 'weeks': [2],
     'surface': 'Hard', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_04', 'name': 'Auckland', 'city': 'Auckland', 'country': 'NZL', 'level': 250, 'weeks': [2],
     'surface': 'Hard', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_05', 'name': 'Montpellier', 'city': 'Montpellier', 'country': 'FRA', 'level': 250, 'weeks': [5],
     'surface': 'Hard (Indoor)', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_06', 'name': 'Cordoba', 'city': 'Cordoba', 'country': 'ARG', 'level': 250, 'weeks': [5],
     'surface': 'Clay', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_07', 'name': 'Dallas', 'city': 'Dallas', 'country': 'USA', 'level': 250, 'weeks': [6],
     'surface': 'Hard (Indoor)', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_08', 'name': 'Marseille', 'city': 'Marseille', 'country': 'FRA', 'level': 250, 'weeks': [6],
     'surface': 'Hard (Indoor)', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_09', 'name': 'Delray Beach', 'city': 'Delray Beach', 'country': 'USA', 'level': 250, 'weeks': [7],
     'surface': 'Hard', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_10', 'name': 'Doha', 'city': 'Doha', 'country': 'QAT', 'level': 250, 'weeks': [8], 'surface': 'Hard',
     'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4, 'wildcards': 3},
    {'id': 'ATP250_11', 'name': 'Santiago', 'city': 'Santiago', 'country': 'CHI', 'level': 250, 'weeks': [9],
     'surface': 'Clay', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_12', 'name': 'Houston', 'city': 'Houston', 'country': 'USA', 'level': 250, 'weeks': [13],
     'surface': 'Clay', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_13', 'name': 'Marrakech', 'city': 'Marrakech', 'country': 'MAR', 'level': 250, 'weeks': [13],
     'surface': 'Clay', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_14', 'name': 'Estoril', 'city': 'Estoril', 'country': 'POR', 'level': 250, 'weeks': [13],
     'surface': 'Clay', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_15', 'name': 'Bucharest', 'city': 'Bucharest', 'country': 'ROU', 'level': 250, 'weeks': [15],
     'surface': 'Clay', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_16', 'name': 'Geneva', 'city': 'Geneva', 'country': 'SUI', 'level': 250, 'weeks': [20],
     'surface': 'Clay', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_17', 'name': 'Lyon', 'city': 'Lyon', 'country': 'FRA', 'level': 250, 'weeks': [20],
     'surface': 'Clay', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_18', 'name': 'Stuttgart', 'city': 'Stuttgart', 'country': 'GER', 'level': 250, 'weeks': [23],
     'surface': 'Grass', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_19', 'name': 's-Hertogenbosch', 'city': 's-Hertogenbosch', 'country': 'NED', 'level': 250,
     'weeks': [23], 'surface': 'Grass', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21,
     'qualifiers': 4, 'wildcards': 3},
    {'id': 'ATP250_20', 'name': 'Mallorca', 'city': 'Mallorca', 'country': 'ESP', 'level': 250, 'weeks': [25],
     'surface': 'Grass', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_21', 'name': 'Newport', 'city': 'Newport', 'country': 'USA', 'level': 250, 'weeks': [28],
     'surface': 'Grass', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_22', 'name': 'Bastad', 'city': 'Bastad', 'country': 'SWE', 'level': 250, 'weeks': [28],
     'surface': 'Clay', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_23', 'name': 'Umag', 'city': 'Umag', 'country': 'CRO', 'level': 250, 'weeks': [29],
     'surface': 'Clay', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_24', 'name': 'Atlanta', 'city': 'Atlanta', 'country': 'USA', 'level': 250, 'weeks': [29],
     'surface': 'Hard', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_25', 'name': 'Kitzbuhel', 'city': 'Kitzbuhel', 'country': 'AUT', 'level': 250, 'weeks': [30],
     'surface': 'Clay', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_26', 'name': 'Los Cabos', 'city': 'Los Cabos', 'country': 'MEX', 'level': 250, 'weeks': [30],
     'surface': 'Hard', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_27', 'name': 'Winston-Salem', 'city': 'Winston-Salem', 'country': 'USA', 'level': 250, 'weeks': [33],
     'surface': 'Hard', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_28', 'name': 'Chengdu', 'city': 'Chengdu', 'country': 'CHN', 'level': 250, 'weeks': [37],
     'surface': 'Hard', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_29', 'name': 'Zhuhai', 'city': 'Zhuhai', 'country': 'CHN', 'level': 250, 'weeks': [37],
     'surface': 'Hard', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_30', 'name': 'Astana', 'city': 'Astana', 'country': 'KAZ', 'level': 250, 'weeks': [38],
     'surface': 'Hard (Indoor)', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_31', 'name': 'Stockholm', 'city': 'Stockholm', 'country': 'SWE', 'level': 250, 'weeks': [41],
     'surface': 'Hard (Indoor)', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_32', 'name': 'Antwerp', 'city': 'Antwerp', 'country': 'BEL', 'level': 250, 'weeks': [41],
     'surface': 'Hard (Indoor)', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_33', 'name': 'Metz', 'city': 'Metz', 'country': 'FRA', 'level': 250, 'weeks': [44],
     'surface': 'Hard (Indoor)', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_34', 'name': 'Gijon', 'city': 'Gijon', 'country': 'ESP', 'level': 250, 'weeks': [44],
     'surface': 'Hard (Indoor)', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_35', 'name': 'Naples', 'city': 'Naples', 'country': 'ITA', 'level': 250, 'weeks': [42],
     'surface': 'Hard', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_36', 'name': 'Seoul', 'city': 'Seoul', 'country': 'KOR', 'level': 250, 'weeks': [38],
     'surface': 'Hard', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_37', 'name': 'Sofia', 'city': 'Sofia', 'country': 'BUL', 'level': 250, 'weeks': [38],
     'surface': 'Hard (Indoor)', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_38', 'name': 'Tel Aviv', 'city': 'Tel Aviv', 'country': 'ISR', 'level': 250, 'weeks': [38],
     'surface': 'Hard (Indoor)', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_39', 'name': 'Pune', 'city': 'Pune', 'country': 'IND', 'level': 250, 'weeks': [1], 'surface': 'Hard',
     'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4, 'wildcards': 3},

    # --- Pool Candidate 250s (20 tournaments for variety) ---
    {'id': 'ATP250_P01', 'name': 'Costa do Sauipe', 'city': 'Costa do Sauipe', 'country': 'BRA', 'level': 250,
     'weeks': [7], 'surface': 'Clay', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_P02', 'name': 'Sydney', 'city': 'Sydney', 'country': 'AUS', 'level': 250, 'weeks': [2],
     'surface': 'Hard', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_P03', 'name': 'New York', 'city': 'New York', 'country': 'USA', 'level': 250, 'weeks': [6],
     'surface': 'Hard (Indoor)', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_P04', 'name': 'Budapest', 'city': 'Budapest', 'country': 'HUN', 'level': 250, 'weeks': [15],
     'surface': 'Clay', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_P05', 'name': 'Istanbul', 'city': 'Istanbul', 'country': 'TUR', 'level': 250, 'weeks': [15],
     'surface': 'Clay', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_P06', 'name': 'Rosmalen', 'city': 'Rosmalen', 'country': 'NED', 'level': 250, 'weeks': [23],
     'surface': 'Grass', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_P07', 'name': 'Los Angeles', 'city': 'Los Angeles', 'country': 'USA', 'level': 250, 'weeks': [29],
     'surface': 'Hard', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_P08', 'name': 'Bogota', 'city': 'Bogota', 'country': 'COL', 'level': 250, 'weeks': [29],
     'surface': 'Hard', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_P09', 'name': 'Moscow', 'city': 'Moscow', 'country': 'RUS', 'level': 250, 'weeks': [41],
     'surface': 'Hard (Indoor)', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_P10', 'name': 'Copenhagen', 'city': 'Copenhagen', 'country': 'DEN', 'level': 250, 'weeks': [41],
     'surface': 'Hard (Indoor)', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_P11', 'name': 'Warsaw', 'city': 'Warsaw', 'country': 'POL', 'level': 250, 'weeks': [29],
     'surface': 'Clay', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_P12', 'name': 'Bangkok', 'city': 'Bangkok', 'country': 'THA', 'level': 250, 'weeks': [37],
     'surface': 'Hard', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_P13', 'name': 'Zagreb', 'city': 'Zagreb', 'country': 'CRO', 'level': 250, 'weeks': [5],
     'surface': 'Hard (Indoor)', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_P14', 'name': 'San Jose', 'city': 'San Jose', 'country': 'USA', 'level': 250, 'weeks': [6],
     'surface': 'Hard (Indoor)', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_P15', 'name': 'Quito', 'city': 'Quito', 'country': 'ECU', 'level': 250, 'weeks': [5],
     'surface': 'Clay', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_P16', 'name': 'Antalya', 'city': 'Antalya', 'country': 'TUR', 'level': 250, 'weeks': [25],
     'surface': 'Grass', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_P17', 'name': 'Shenzhen', 'city': 'Shenzhen', 'country': 'CHN', 'level': 250, 'weeks': [37],
     'surface': 'Hard', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_P18', 'name': 'Valencia', 'city': 'Valencia', 'country': 'ESP', 'level': 250, 'weeks': [42],
     'surface': 'Hard (Indoor)', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_P19', 'name': 'Ho Chi Minh City', 'city': 'Ho Chi Minh City', 'country': 'VIE', 'level': 250,
     'weeks': [41], 'surface': 'Hard', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
    {'id': 'ATP250_P20', 'name': 'Casablanca', 'city': 'Casablanca', 'country': 'MAR', 'level': 250, 'weeks': [13],
     'surface': 'Clay', 'status': 'Rotating', 'draw_size': 28, 'main_draw_entrants': 21, 'qualifiers': 4,
     'wildcards': 3},
]